name: Update GitHub Bio

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  update_bio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate dynamic bio content
        id: bio
        run: |
          DATE=$(date '+%Y-%m-%d')
          BIO_CONTENT="ğŸ’¼ Mobile Developer @miniclip ğŸ“²ğŸ‘¾\\nğŸ“š Phd Student @iade-pt ğŸ‘¨ğŸ»â€ğŸ’» \\n\\n Today is $DATE."
          echo "::set-output name=bio::$BIO_CONTENT"

      - name: Update GitHub Bio
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"bio\": \"${{ steps.bio.outputs.bio }}\"}" \
            https://api.github.com/user
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

